# Generated by Django 3.0.7 on 2020-10-24 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('pk_num', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=50)),
                ('item_num', models.IntegerField(default=0)),
                ('limit_time', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('contents', models.TextField(max_length=1000)),
                ('dates', models.DateTimeField(auto_now=True)),
                ('remain', models.IntegerField(default=0)),
                ('remain_time', models.IntegerField(default=0)),
                ('outdate', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ItemShare',
            fields=[
                ('pk_num', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=50)),
                ('item_num', models.IntegerField(default=0)),
                ('limit_time', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('contents', models.TextField(max_length=1000)),
                ('dates', models.DateTimeField(auto_now=True)),
                ('remain', models.IntegerField(default=0)),
                ('remain_time', models.IntegerField(default=0)),
                ('outdate', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ShareAccept',
            fields=[
                ('pk_num', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('share_location', models.CharField(blank=True, max_length=100)),
                ('share_num', models.IntegerField(default=0)),
                ('share_email', models.CharField(blank=True, max_length=100)),
                ('share_phone', models.CharField(blank=True, max_length=15)),
                ('share_contents', models.TextField(blank=True, max_length=1000)),
                ('dates', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotteryapp.ItemShare')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestAccept',
            fields=[
                ('pk_num', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('request_location', models.CharField(blank=True, max_length=100)),
                ('request_num', models.IntegerField(default=0)),
                ('request_email', models.CharField(blank=True, max_length=100)),
                ('request_phone', models.CharField(blank=True, max_length=15)),
                ('request_contents', models.TextField(blank=True, max_length=1000)),
                ('dates', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotteryapp.ItemRequest')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100)),
                ('item_num', models.IntegerField(default=0)),
                ('order_date', models.DateField(default=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
    ]
