# Generated by Django 3.0.8 on 2020-10-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('pk_num', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=50)),
                ('item_num', models.IntegerField(default=0)),
                ('limit_time', models.TimeField(auto_now=True)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('contents', models.TextField(max_length=1000)),
                ('dates', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ItemShare',
            fields=[
                ('pk_num', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=50)),
                ('item_num', models.IntegerField(default=0)),
                ('limit_time', models.TimeField(auto_now=True)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('contents', models.TextField(max_length=1000)),
                ('dates', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ShareAccept',
            fields=[
                ('pk_num', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotteryapp.ItemShare')),
            ],
        ),
        migrations.CreateModel(
            name='RequestAccept',
            fields=[
                ('pk_num', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotteryapp.ItemRequest')),
            ],
        ),
    ]
