# Generated by Django 3.1.2 on 2020-10-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyrequest',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='dummyshare',
            name='minute',
        ),
        migrations.AddField(
            model_name='dummyrequest',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dummyrequest',
            name='limit_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dummyrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='dummyshare',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dummyshare',
            name='limit_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dummyshare',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='dummyrequest',
            name='contents',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dummyshare',
            name='contents',
            field=models.TextField(max_length=1000),
        ),
    ]
