# Generated by Django 3.1.1 on 2020-09-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyrequest',
            name='contents',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dummyrequest',
            name='time',
            field=models.TimeField(),
        ),
    ]
