# Generated by Django 3.1.2 on 2020-10-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareaccept',
            name='target',
        ),
        migrations.DeleteModel(
            name='RequestAccept',
        ),
        migrations.DeleteModel(
            name='ShareAccept',
        ),
    ]
