# Generated by Django 3.1.1 on 2020-09-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryapp', '0002_auto_20200930_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyrequest',
            name='Request',
            field=models.BooleanField(null=True),
        ),
    ]
