# Generated by Django 3.1.2 on 2020-10-05 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('lotteryapp', '0002_auto_20201005_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareAccept',
            fields=[
                ('pk_num', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('share_num', models.IntegerField(default=0)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotteryapp.itemshare')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RequestAccept',
            fields=[
                ('pk_num', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('request_num', models.IntegerField(default=0)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotteryapp.itemrequest')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
