# Generated by Django 3.1.1 on 2020-09-30 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryapp', '0003_dummyrequest_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dummyrequest',
            name='Request',
        ),
        migrations.AddField(
            model_name='dummyrequest',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lotteryapp.dummyitem'),
        ),
    ]
