# Generated by Django 3.1.2 on 2020-10-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryapp', '0003_requestaccept_shareaccept'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestaccept',
            name='request_contents',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='requestaccept',
            name='request_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='requestaccept',
            name='request_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='requestaccept',
            name='request_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='shareaccept',
            name='share_contents',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='shareaccept',
            name='share_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shareaccept',
            name='share_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shareaccept',
            name='share_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
