# Generated by Django 3.1.2 on 2020-10-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryapp', '0005_auto_20201005_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestaccept',
            name='dates',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shareaccept',
            name='dates',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='dates',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='itemshare',
            name='dates',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
