# Generated by Django 3.1.1 on 2020-09-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryapp', '0005_auto_20200930_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('contents', models.TextField(blank=True)),
                ('minute', models.IntegerField()),
                ('item', models.CharField(max_length=50)),
                ('item_num', models.IntegerField()),
                ('dates', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DummyItem',
        ),
        migrations.RemoveField(
            model_name='keyval',
            name='container',
        ),
        migrations.RemoveField(
            model_name='dummyrequest',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='dummyrequest',
            name='time',
        ),
        migrations.AddField(
            model_name='dummyrequest',
            name='dates',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dummyrequest',
            name='item',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dummyrequest',
            name='item_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dummyrequest',
            name='minute',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Dicty',
        ),
        migrations.DeleteModel(
            name='KeyVal',
        ),
    ]
