# Generated by Django 3.1.1 on 2020-10-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryapp', '0006_auto_20200930_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='dummyrequest',
            name='pk_num',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
