# Generated by Django 3.1.2 on 2020-10-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryapp', '0007_auto_20201005_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='outdate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemshare',
            name='outdate',
            field=models.BooleanField(default=False),
        ),
    ]
