# Generated by Django 3.1.1 on 2020-10-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryapp', '0007_auto_20201001_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyrequest',
            name='pk_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
