# Generated by Django 3.1.1 on 2020-10-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('lotteryapp', '0008_auto_20201001_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyrequest',
            name='user_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='dummyrequest',
            name='contents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dummyrequest',
            name='item',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dummyrequest',
            name='item_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dummyrequest',
            name='minute',
            field=models.IntegerField(),
        ),
    ]
