# Generated by Django 3.1.2 on 2020-10-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryapp', '0008_auto_20201006_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemshare',
            name='pk_num',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requestaccept',
            name='pk_num',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shareaccept',
            name='pk_num',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
