# Generated by Django 3.1.1 on 2020-10-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryapp', '0009_auto_20201001_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dummyrequest',
            old_name='user_link',
            new_name='author',
        ),
    ]
