# Generated by Django 3.1.1 on 2020-10-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryapp', '0010_auto_20201009_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='remain_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemshare',
            name='remain_time',
            field=models.IntegerField(default=0),
        ),
    ]
