# Generated by Django 3.1.1 on 2020-10-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('lotteryapp', '0010_auto_20201001_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyshare',
            name='id',
        ),
        migrations.AddField(
            model_name='dummyshare',
            name='pk_num',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dummyrequest',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user.user'),
        ),
        migrations.AlterField(
            model_name='dummyrequest',
            name='item_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dummyrequest',
            name='minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dummyrequest',
            name='pk_num',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dummyshare',
            name='contents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dummyshare',
            name='item_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dummyshare',
            name='minute',
            field=models.IntegerField(default=0),
        ),
    ]
