# Generated by Django 3.1.2 on 2020-10-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_detail',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
